%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Philip\Documents\MATLAB\data_20151104.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/04 13:53:30

%% Initialize variables.
filename = 'C:\Users\Vishakha\Google Drive\Fall_2015\Practicum\Data\WalkingBy1.txt';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
temp = dataArray{:, 1};
id = dataArray{:, 2};
light = dataArray{:, 3};
timestamp = dataArray{:, 4};
acc_z = dataArray{:, 5};
acc_y = dataArray{:, 6};
acc_x = dataArray{:, 7};
motion = dataArray{:, 8};
pressure = dataArray{:, 9};
humid = dataArray{:, 10};
acc = sqrt((acc_x.*acc_x)+(acc_y.*acc_y)+(acc_z.*acc_z));

%% Clear temporary variables
%{
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

hpFilt = designfilt('highpassfir','StopbandFrequency',0.5, ...
         'PassbandFrequency',0.6,'PassbandRipple',0.5, ...
         'StopbandAttenuation',60,'DesignMethod','kaiserwin');
fvtool(hpFilt);
temp_hp = filter(hpFilt,temp);
figure;
plot(temp_hp);
%}


lpFilt = designfilt('lowpassfir','PassbandFrequency',0.2, ...
         'StopbandFrequency',0.3,'PassbandRipple',0.5, ...
         'StopbandAttenuation',40,'DesignMethod','kaiserwin');
light_lp = filter(lpFilt,acc);
light_diff_lp = filter(lpFilt,diff(acc));
% fvtool(lpFilt);
%figure;
%plot(diff(temp));
%figure;
%plot(temp_deff_lp);

%{
subplot(3, 2, 1), plot(motion);
title('motion');
subplot(3, 2, 3), plot(light);
title('light');
subplot(3, 2, 5), plot(pressure);
title('pressure');

subplot(3, 2, 2), plot(humid);
title('humid');
subplot(3, 2, 4), plot(temp);
title('temp');
subplot(3, 2, 6), plot(acc);
title('normalized acc');
%}

[acc_sig, win] = slidingWin(acc, 10, 4);
light_th = acc(1) + 400;
%light_sig = threshold(motion, light_th, 0);

% %[temp_sig, win] = slidingWin(temp_deff_lp, 80, 0.2);
% subplot(3, 1, 1), plot(light);
% title('light');
% subplot(3, 1, 2), plot(diff(light));
% title('diff');
% subplot(3, 1, 3), plot(light_sig);
% title('predicted');

%{
subplot(2, 1, 1), plot(light);
title('Original sensor data (A)');
subplot(2, 1, 2), plot(light_sig);
title('After threshold (B)');
%}

%{
subplot(3, 2, 1), plot(light);
title('light');
subplot(3, 2, 2), plot(diff(light));
title('diff');
subplot(3, 2, 3), plot(light_sig);
title('predicted (threshold)');

subplot(3, 2, 4), plot(light_lp);
title('light lp');
subplot(3, 2, 5), plot(win);
title('sliding window');
subplot(3, 2, 6), plot(light_diff_lp);
title('predicted diff lp');
%}
%{
subplot(3, 2, 3), plot(light);
title('Light');
subplot(3, 2, 1), plot(motion);
title('Motion');
subplot(3, 2, 2), plot(humid);
title('Humid');

subplot(3, 2, 4), plot(temp);
title('Temperature');
subplot(3, 2, 5), plot(pressure);
title('Pressure');
subplot(3, 2, 6), plot(acc);
title('Acceleration');
%}
%{
subplot(3, 1, 1), plot(motion);
title('Sensor data (A)');
subplot(3, 1, 2), plot(win);
title('After sliding window (B)');
subplot(3, 1, 3), plot(motion_sig);
title('After threshold (C)');
%}
%{
subplot(3, 2, 1), plot(motion);
title('light');
subplot(3, 2, 2), plot(diff(motion));
title('diff');
subplot(3, 2, 3), plot(motion_sig);
title('predicted (sw)');

subplot(3, 2, 4), plot(light_lp);
title('light lp');
subplot(3, 2, 5), plot(win);
title('sliding window');
subplot(3, 2, 6), plot(light_diff_lp);
title('predicted diff lp');
%}
subplot(3, 2, 1), plot(acc);
title('light');
subplot(3, 2, 2), plot(diff(acc));
title('diff');
subplot(3, 2, 3), plot(acc_sig);
title('predicted (sw)');

subplot(3, 2, 4), plot(light_lp);
title('light lp');
subplot(3, 2, 5), plot(win);
title('sliding window');
subplot(3, 2, 6), plot(light_diff_lp);
title('predicted diff lp');
